<?php

use Idea\Models\RolePermission;

use Illuminate\Database\Seeder;

class RolePermissionTableSeeder extends Seeder {

  /**
   * Run the database seeds.
   *
   * @return void
   */
  public function run() {
    //
    $rolePermissions = [
      ['id' => 1, 'permission_id' =>  1, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 2, 'permission_id' =>  1, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 3, 'permission_id' =>  2, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 4, 'permission_id' =>  2, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 5, 'permission_id' =>  3, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 6, 'permission_id' =>  3, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 7, 'permission_id' =>  4, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 8, 'permission_id' =>  4, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 9, 'permission_id' =>  5, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 10, 'permission_id' =>  5, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 11, 'permission_id' =>  6, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 12, 'permission_id' =>  6, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 13, 'permission_id' =>  7, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 14, 'permission_id' =>  7, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 15, 'permission_id' =>  8, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 16, 'permission_id' =>  8, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 17, 'permission_id' =>  9, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 18, 'permission_id' =>  9, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 19, 'permission_id' =>  10, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 20, 'permission_id' =>  10, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 21, 'permission_id' =>  11, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 22, 'permission_id' =>  11, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 23, 'permission_id' =>  12, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 24, 'permission_id' =>  12, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 25, 'permission_id' =>  13, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 26, 'permission_id' =>  13, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 27, 'permission_id' =>  14, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 28, 'permission_id' =>  14, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 32, 'permission_id' =>  1, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 33, 'permission_id' =>  1, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 34, 'permission_id' =>  2, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 35, 'permission_id' =>  2, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 36, 'permission_id' =>  3, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 37, 'permission_id' =>  3, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 38, 'permission_id' =>  4, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 39, 'permission_id' =>  4, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 40, 'permission_id' =>  5, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 41, 'permission_id' =>  5, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 42, 'permission_id' =>  6, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 43, 'permission_id' =>  6, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 44, 'permission_id' =>  7, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 45, 'permission_id' =>  7, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 46, 'permission_id' =>  8, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 47, 'permission_id' =>  8, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 48, 'permission_id' =>  9, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 49, 'permission_id' =>  9, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 50, 'permission_id' =>  10, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 51, 'permission_id' =>  10, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 52, 'permission_id' =>  11, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 53, 'permission_id' =>  11, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 54, 'permission_id' =>  12, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 55, 'permission_id' =>  12, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 56, 'permission_id' =>  13, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 57, 'permission_id' =>  13, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 58, 'permission_id' =>  14, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 59, 'permission_id' =>  14, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 60, 'permission_id' =>  1, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 62, 'permission_id' =>  2, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 63, 'permission_id' =>  2, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 64, 'permission_id' =>  3, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 65, 'permission_id' =>  3, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 66, 'permission_id' =>  4, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 67, 'permission_id' =>  4, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 68, 'permission_id' =>  5, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 69, 'permission_id' =>  5, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 70, 'permission_id' =>  6, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 71, 'permission_id' =>  6, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 72, 'permission_id' =>  7, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 73, 'permission_id' =>  7, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 74, 'permission_id' =>  8, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 75, 'permission_id' =>  8, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 76, 'permission_id' =>  9, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 77, 'permission_id' =>  9, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 78, 'permission_id' =>  10, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 79, 'permission_id' =>  10, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 80, 'permission_id' =>  11, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 81, 'permission_id' =>  11, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 82, 'permission_id' =>  12, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 83, 'permission_id' =>  12, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 84, 'permission_id' =>  13, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 85, 'permission_id' =>  13, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 86, 'permission_id' =>  14, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 87, 'permission_id' =>  14, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 88, 'permission_id' =>  15, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 89, 'permission_id' =>  15, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 90, 'permission_id' =>  15, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 91, 'permission_id' =>  16, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 92, 'permission_id' =>  16, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 93, 'permission_id' =>  16, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 95, 'permission_id' =>  1, 'role_id' => 6, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 96, 'permission_id' =>  2, 'role_id' => 6, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 97, 'permission_id' =>  3, 'role_id' => 6, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 98, 'permission_id' =>  4, 'role_id' => 6, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 99, 'permission_id' =>  5, 'role_id' => 6, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 100, 'permission_id' =>  6, 'role_id' => 6, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 101, 'permission_id' =>  7, 'role_id' => 6, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 102, 'permission_id' =>  8, 'role_id' => 6, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 103, 'permission_id' =>  9, 'role_id' => 6, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 104, 'permission_id' =>  10, 'role_id' => 6, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 105, 'permission_id' =>  11, 'role_id' => 6, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 106, 'permission_id' =>  12, 'role_id' => 6, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 107, 'permission_id' =>  13, 'role_id' => 6, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 109, 'permission_id' =>  17, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 110, 'permission_id' =>  17, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 111, 'permission_id' =>  17, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 112, 'permission_id' =>  17, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 113, 'permission_id' =>  17, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 114, 'permission_id' =>  17, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 115, 'permission_id' =>  17, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 116, 'permission_id' =>  17, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 117, 'permission_id' =>  17, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 118, 'permission_id' =>  17, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 120, 'permission_id' =>  18, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 121, 'permission_id' =>  18, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 122, 'permission_id' =>  18, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 123, 'permission_id' =>  18, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 124, 'permission_id' =>  18, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 125, 'permission_id' =>  18, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 126, 'permission_id' =>  18, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 127, 'permission_id' =>  18, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 128, 'permission_id' =>  18, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 129, 'permission_id' =>  18, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 131, 'permission_id' =>  19, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 132, 'permission_id' =>  19, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 133, 'permission_id' =>  19, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 134, 'permission_id' =>  19, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 135, 'permission_id' =>  19, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 136, 'permission_id' =>  19, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 137, 'permission_id' =>  19, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 138, 'permission_id' =>  19, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 139, 'permission_id' =>  19, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 140, 'permission_id' =>  19, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 142, 'permission_id' =>  20, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 143, 'permission_id' =>  20, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 144, 'permission_id' =>  20, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 145, 'permission_id' =>  20, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 146, 'permission_id' =>  20, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 147, 'permission_id' =>  20, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 148, 'permission_id' =>  20, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 149, 'permission_id' =>  20, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 150, 'permission_id' =>  20, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 151, 'permission_id' =>  20, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 153, 'permission_id' =>  21, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 154, 'permission_id' =>  21, 'role_id' => 1, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 155, 'permission_id' =>  21, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 156, 'permission_id' =>  21, 'role_id' => 2, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 157, 'permission_id' =>  21, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 158, 'permission_id' =>  21, 'role_id' => 3, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 159, 'permission_id' =>  21, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 160, 'permission_id' =>  21, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 161, 'permission_id' =>  21, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 162, 'permission_id' =>  21, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 164, 'permission_id' =>  15, 'role_id' => 6, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 167, 'permission_id' =>  9, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 168, 'permission_id' =>  11, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 169, 'permission_id' =>  12, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 170, 'permission_id' =>  13, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 171, 'permission_id' =>  14, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 172, 'permission_id' =>  15, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 173, 'permission_id' =>  10, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 174, 'permission_id' =>  11, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 175, 'permission_id' =>  12, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 176, 'permission_id' =>  13, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 177, 'permission_id' =>  14, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 178, 'permission_id' =>  15, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 179, 'permission_id' =>  1, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 180, 'permission_id' =>  2, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 181, 'permission_id' =>  3, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 182, 'permission_id' =>  4, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 183, 'permission_id' =>  5, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 184, 'permission_id' =>  6, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 185, 'permission_id' =>  7, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 186, 'permission_id' =>  8, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 187, 'permission_id' =>  9, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 188, 'permission_id' =>  10, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 189, 'permission_id' =>  11, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 190, 'permission_id' =>  12, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 191, 'permission_id' =>  13, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 192, 'permission_id' =>  15, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 195, 'permission_id' =>  10, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 196, 'permission_id' =>  11, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 197, 'permission_id' =>  12, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 198, 'permission_id' =>  13, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 199, 'permission_id' =>  14, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 200, 'permission_id' =>  15, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 202, 'permission_id' =>  7, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 203, 'permission_id' =>  7, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 204, 'permission_id' =>  7, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 205, 'permission_id' =>  7, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 206, 'permission_id' =>  10, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 208, 'permission_id' =>  10, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 211, 'permission_id' =>  6, 'role_id' => 1, 'action_id' => 4, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 212, 'permission_id' =>  6, 'role_id' => 2, 'action_id' => 4, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 213, 'permission_id' =>  6, 'role_id' => 3, 'action_id' => 4, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 216, 'permission_id' =>  15, 'role_id' => 1, 'action_id' => 3, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 217, 'permission_id' =>  15, 'role_id' => 2, 'action_id' => 3, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 218, 'permission_id' =>  15, 'role_id' => 3, 'action_id' => 3, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 219, 'permission_id' =>  15, 'role_id' => 4, 'action_id' => 3, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 220, 'permission_id' =>  15, 'role_id' => 5, 'action_id' => 3, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 221, 'permission_id' =>  15, 'role_id' => 8, 'action_id' => 3, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],


      ['id' => 225, 'permission_id' =>  2, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 226, 'permission_id' =>  2, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 227, 'permission_id' =>  3, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 228, 'permission_id' =>  3, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 229, 'permission_id' =>  4, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 230, 'permission_id' =>  4, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 231, 'permission_id' =>  5, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 232, 'permission_id' =>  5, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 233, 'permission_id' =>  6, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 234, 'permission_id' =>  6, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 235, 'permission_id' =>  7, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 236, 'permission_id' =>  7, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 237, 'permission_id' =>  8, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 238, 'permission_id' =>  8, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 239, 'permission_id' =>  9, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 240, 'permission_id' =>  9, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 241, 'permission_id' =>  10, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 242, 'permission_id' =>  10, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 243, 'permission_id' =>  11, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 245, 'permission_id' =>  11, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 246, 'permission_id' =>  12, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 247, 'permission_id' =>  12, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 248, 'permission_id' =>  13, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 249, 'permission_id' =>  13, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 250, 'permission_id' =>  14, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 251, 'permission_id' =>  14, 'role_id' => 4, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 252, 'permission_id' =>  16, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 253, 'permission_id' =>  15, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],


      ['id' => 254, 'permission_id' =>  2, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 255, 'permission_id' =>  2, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 256, 'permission_id' =>  3, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 257, 'permission_id' =>  3, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 258, 'permission_id' =>  4, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 259, 'permission_id' =>  4, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 260, 'permission_id' =>  5, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 261, 'permission_id' =>  5, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 262, 'permission_id' =>  6, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 263, 'permission_id' =>  8, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 264, 'permission_id' =>  8, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 265, 'permission_id' =>  14, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 266, 'permission_id' =>  16, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 267, 'permission_id' =>  16, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 268, 'permission_id' =>  15, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],

      ['id' => 269, 'permission_id' =>  1, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 270, 'permission_id' =>  2, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 271, 'permission_id' =>  3, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 272, 'permission_id' =>  4, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 273, 'permission_id' =>  5, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 274, 'permission_id' =>  6, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 275, 'permission_id' =>  7, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 276, 'permission_id' =>  8, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 277, 'permission_id' =>  9, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 278, 'permission_id' =>  10, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 279, 'permission_id' =>  11, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 280, 'permission_id' =>  12, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 281, 'permission_id' =>  13, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 283, 'permission_id' =>  15, 'role_id' => 8, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 284, 'permission_id' =>  15, 'role_id' => 8, 'action_id' => 3, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 285, 'permission_id' =>  16, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 286, 'permission_id' =>  16, 'role_id' => 8, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],

      ['id' => 287, 'permission_id' =>  22, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 288, 'permission_id' =>  22, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 290, 'permission_id' =>  22, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      

      ['id' => 295, 'permission_id' =>  23, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 296, 'permission_id' =>  23, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 297, 'permission_id' =>  23, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 299, 'permission_id' =>  23, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 301, 'permission_id' =>  23, 'role_id' => 7, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 302, 'permission_id' =>  23, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],

      ['id' => 303, 'permission_id' =>  24, 'role_id' => 1, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 304, 'permission_id' =>  24, 'role_id' => 2, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 305, 'permission_id' =>  24, 'role_id' => 3, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 306, 'permission_id' =>  24, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 307, 'permission_id' =>  24, 'role_id' => 5, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 309, 'permission_id' =>  24, 'role_id' => 7, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 310, 'permission_id' =>  24, 'role_id' => 8, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],

      ['id' => 311, 'permission_id' =>  9, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 312, 'permission_id' =>  12, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],
      ['id' => 313, 'permission_id' =>  13, 'role_id' => 5, 'action_id' => 2, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],

      ['id' => 314, 'permission_id' =>  23, 'role_id' => 4, 'action_id' => 1, 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s') ],

    ];
    RolePermission::insert($rolePermissions);
  }
}
